openapi: 3.0.0
info:
  title: portfolio
  version: '1.0'
  contact:
    name: nekochans
    url: 'https://github.com/nekochans/portfolio-backend/issues'
  termsOfService: 'https://github.com/nekochans/portfolio-backend'
  license:
    name: MIT
servers:
  - url: 'http://localhost:8888'
paths:
  '/members/{id}':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    get:
      summary: fetchMember
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
              examples:
                example-1:
                  value:
                    id: 1
                    githubUserName: keitakn
                    githubPicture: 'https://avatars3.githubusercontent.com/u/11032365'
                    cvUrl: 'https://github.com/keitakn/cv'
          headers:
            X-Request-Id:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          headers:
            X-Request-Id:
              schema:
                type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                example-1:
                  value:
                    code: 404
                    message: Member Not Found
          headers:
            X-Request-Id:
              schema:
                type: string
        '500':
          description: Internal Server Error
          headers:
            X-Request-Id:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      operationId: fetchMember
      description: Memberを1件取得する
components:
  schemas:
    Member:
      title: Member
      type: object
      x-examples:
        example-1:
          id: 1
          githubUserName: keitakn
          githubPicture: 'https://avatars3.githubusercontent.com/u/11032365'
          cvUrl: 'https://github.com/keitakn/cv'
      properties:
        id:
          type: integer
        githubUserName:
          type: string
        githubPicture:
          type: string
        cvUrl:
          type: string
      description: メンバーモデル
    Error:
      title: Error
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      description: エラーモデル
      x-examples:
        example-1:
          code: 404
          message: Member Not Found
